# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e07d68bf349c1556b976d97b25a8da9f59fb4e00a3b6b77817b13dd2544f986d3d206d52c17cb690f64cf1d7259b227d40f2e7cff3f49eab49620a89d90141b

test:
  secret_key_base: 18c34f9cdd67c1dc0a7aeac8af5bfb2127bb59605bbe0203390750bcf574e62e4bdee66fb09a0ad53d3b2501972fee415dc56941d13628734c2dfe4ecfc203e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
